# **Pour réaliser le bras du Drone avec Tinkercad:**

Aller sur le site [Tinkercad](https://www.tinkercad.com/)  
Créer votre compte puis sur le dashboard selectionner "Créer une conception"

## **Étape 1 : Créer un cylindre**

Faire glisser le cylindre orange du panneau latéral de droite sur le plan de construction.

![Alt Text](Gifs/01.gif)

Cliquer sur les rectangles blancs pour donner au cylindre, une base de 10,00 mm en largeur et en profondeur (la hauteur n’a pas besoin d’être modifiée).

![Alt Text](Gifs/02.gif)

D’autre part, il faut modifier le réglage de la grille en cliquant sur la boîte située en bas à droite et à côté de
« Grille d’accrochage 1,0 mm » et sélectionner 0,25 mm.

![Alt Text](Gifs/03-3.gif)

Puis, sélectionner le cylindre gris dans le panneau de droite.  Toujours à l’aide des carrés blancs, il faut changer les dimensions de la base du cylindre afin de lui donner les valeurs de 7,50 mm en largeur et 7,50 mm en profondeur.  

![Alt Text](Gifs/04.gif)

À l’aide de la flèche noire au sommet, surélever le cylindre de 2,00 mm en hauteur par rapport au plan de travail.  

![Alt Text](Gifs/05-2.gif)


## **Étape 2 : Extruder le cylindre orange**

En maintenant le bouton gauche de la souris, sélectionner les deux cylindres.  Ils devraient apparaître tous deux entourés d’un trait couleur cyan.  Appuyer sur le bouton « Aligner » ( ou bien la touche L ).  
Une grille de sélection apparaît sur le rectangle au niveau du plan de travail.  Cliquer sur les cercles se situant au milieu des segments du rectangle.  Le cylindre gris se situe maintenant au milieu du cylindre orange.

![Alt Text](Gifs/06.gif)

Sélectionner ensuite l’icône « Regrouper » en haut à droite ( ou la touche Ctrl + G ).

![Alt Text](Gifs/07.gif)

Le cylindre orange est maintenant creux.


## **Étape 3 : Ajouter des aérations**

Il faut donc prendre le cylindre gris du panneau latéral.
Grâce aux doubles flèches courbes, il est nécessaire de lui faire effectuer une rotation de 90°.

![Alt Text](Gifs/08.gif)

Lui donner ensuite une hauteur de 7,00 mm, une largeur de 6,00 mm et une profondeur de 20,00 mm.
Grâce à la flèche noire, le surélever de 1,00 mm.

![Alt Text](Gifs/09.gif)

Avec l’outil "Aligner", mettre le cylindre gris au centre du cylindre orange.

![Alt Text](Gifs/10.gif)

Dupliquer le cylindre gris avec le bouton en haut à gauche ( ou bien la touche Ctrl + D ) et grâce à la flèche noire, le surélever de 10,00 mm.

![Alt Text](Gifs/11.gif)

Sélectionner les trois cylindres et cliquer de nouveau sur « Regrouper ».

![Alt Text](Gifs/12.gif)

Le cylindre orange est maintenant percé de quatre ovales.


## **Étape 4 : Réaliser le bras**

Sélectionner la boîte rouge dans le panneau latéral droit.

![Alt Text](Gifs/13.gif)

Après avoir placé la boîte rouge sur le plan de travail, il faut lui donner une largeur de 6,50 mm, une hauteur de 6,50 mm et une profondeur de 20,00 mm.

![Alt Text](Gifs/14.gif)

Prendre un cube gris, il est nécessaire de lui donner les dimensions suivantes :
3,25 mm de largeur, 3,25 mm de hauteur et 10,00 mm de profondeur.

![Alt Text](Gifs/15.gif)

Insérer le rectangle gris dans le rectangle rouge en sélectionnant les deux rectangles.  Ensuite, avec l'outil "aligner", centrer le rectangle gris au bord du rectangle rouge en cliquant sur les points noirs situés à mi-hauteur, au milieu et enfin au bord gauche du rectangle rouge.

![Alt Text](Gifs/16.gif)

Déplacer vers arrière le rectangle rouge de 1,00 mm sans déplacement latéralement, puis regrouper les deux rectangles.  
(Astuce : Presser la touche ⇧ SHIFT après avoir cliqué avec la souris permet de verrouiller le déplacement dans une seule direction)

![Alt Text](Gifs/17.gif)

Maintenant, cliquer sur la forme "biseau" et la poser sur le plan de construction. Ensuite, faire effectuer à cette forme une rotation de 90° de sa base vers la gauche et une autre rotation de 90° vers le bas sur son axe vertical.

![Alt Text](Gifs/18.gif)

Donner au biseau une hauteur de 13,50 mm et une largeur de 6,50 mm.

![Alt Text](Gifs/19.gif)

Faire fusionner avec l'outil "aligner" le rectangle et le biseau.

![Alt Text](Gifs/20.gif)

Surélever le rectangle de 13,50 mm pour le poser sur le biseau et regrouper les deux pièces entre elles.

![Alt Text](Gifs/21.gif)

Aligner cette nouvelle pièce avec le cylindre précédemment extrudé.

![Alt Text](Gifs/22.gif)

 Déplacer la pièce de 8,25 mm vers la droite et fusionner l'ensemble.

![Alt Text](Gifs/23.gif)

La pièce est maintenant terminée et prête à être imprimée !

<script src="https://github.com/emlyon/makerstime/blob/master/STL/Drone_Arm.stl"></script>
