<html lang="fr">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>makers' lab</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    <link href="../css/style.min.css" rel="stylesheet">

    <script src="../js/isBrightspace.js"></script>
</head>

<body>

<font size="4">

<div class="container">

  <h4>Pour réaliser le bras du Drone avec Tinkercad :</h4>

<br>

<script src="https://embed.github.com/view/3d/emlyon/makerstime/master/STL/Drone_Arm.stl?height=600&width=1070"></script>

<br>

<p> Aller sur le site <a href="https://www.tinkercad.com/">Tinkercad</a>
  <br /> Créer votre compte puis sur le dashboard selectionner "Creer une conception" </p>

<br>

<img src="https://emlyon.github.io/makerstime/Tuto01MP4/Tinkercad_Fr.png" width="1070" height="600">

<br><br>


<h5>Étape 1 : Créer un cylindre </h5>

<p> Faire glisser le cylindre orange du panneau latéral de droite sur le plan de construction. </p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/01.mp4" type="video/mp4">
</video>

<p> Cliquer sur les rectangles blancs pour donner au cylindre, une base de 10,00 mm en largeur et en profondeur
  <br /> (la hauteur n’a pas besoin d’être modifiée).</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/02.mp4" type="video/mp4">
</video>

<p> D’autre part, il faut modifier le réglage de la grille en cliquant sur la boîte située en bas à droite et à côté de :
  <br /> « Grille d’accrochage 1,0 mm » et sélectionner 0,25 mm.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/03.mp4" type="video/mp4">
</video>

<p> Puis, sélectionner le cylindre gris dans le panneau de droite.
  <br /> Toujours à l’aide des carrés blancs, il faut changer les dimensions de la base du cylindre afin de lui donner les valeurs de 7,50 mm en largeur et 7,50 mm en profondeur.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/04.mp4" type="video/mp4">
</video>

<p> À l’aide de la flèche noire au sommet, surélever le cylindre de 2,00 mm en hauteur par rapport au plan de travail.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/05.mp4" type="video/mp4">
</video>

<br><br><br>

<h5>Étape 2 : Extruder le cylindre orange </h5>

<p> En maintenant le bouton gauche de la souris, sélectionner les deux cylindres.
  <br / > Ils devraient apparaître tous deux entourés d’un trait couleur cyan.
    <br /> Appuyer sur le bouton « Aligner » ( ou bien la touche L ).
      <br /> Une grille de sélection apparaît sur le rectangle au niveau du plan de travail.
        <br />Cliquer sur les cercles se situant au milieu des segments du rectangle.
          <br /> Le cylindre gris se situe maintenant au milieu du cylindre orange.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/06.mp4" type="video/mp4">
</video>

<p> Sélectionner ensuite l’icône « Regrouper » en haut à droite ( ou la touche Ctrl + G ).</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/07.mp4" type="video/mp4">
</video>

<p> Le cylindre orange est maintenant creux.</p>

<br><br><br>

<h5>Étape 3 : Ajouter des aérations</h5>

<p> Il faut donc prendre le cylindre gris du panneau latéral.
  <br /> Grâce aux doubles flèches courbes, il est nécessaire de lui faire effectuer une rotation de 90°.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/08.mp4" type="video/mp4">
</video>

<p> Lui donner ensuite une hauteur de 7,00 mm, une largeur de 6,00 mm et une profondeur de 20,00 mm.
  <br /> Grâce à la flèche noire, le surélever de 1,00 mm.</p>


<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/09.mp4" type="video/mp4">
</video>

<p>Avec l’outil "Aligner", mettre le cylindre gris au centre du cylindre orange.</p>


<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/10.mp4" type="video/mp4">
</video>

<p> Dupliquer le cylindre gris avec le bouton en haut à gauche ( ou bien la touche Ctrl + D ) et grâce à la flèche noire, le surélever de 10,00 mm.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/11.mp4" type="video/mp4">
</video>

<p> Sélectionner les trois cylindres et cliquer de nouveau sur « Regrouper ».</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/12.mp4" type="video/mp4">
</video>

<p> Le cylindre orange est maintenant percé de quatre ovales.</p>

<br><br><br>

<h5>Étape 4 : Réaliser le bras</h5>

<p> Sélectionner la boîte rouge dans le panneau latéral droit.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/13.mp4" type="video/mp4">
</video>

<p> Après avoir placé la boîte rouge sur le plan de travail, il faut lui donner une largeur de 6,50 mm, une hauteur de 6,50 mm et une profondeur de 20,00 mm.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/14.mp4" type="video/mp4">
</video>

<p> Prendre un cube gris, il est nécessaire de lui donner les dimensions suivantes :
  <br /> 3,25 mm de largeur, 3,25 mm de hauteur et 10,00 mm de profondeur.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/15.mp4" type="video/mp4">
</video>

<p> Insérer le rectangle gris dans le rectangle rouge en sélectionnant les deux rectangles.
  <br /> Ensuite, avec l'outil "aligner", centrer le rectangle gris au bord du rectangle rouge en cliquant sur les points noirs situés à mi-hauteur, au milieu et enfin au bord gauche du rectangle rouge.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/16.mp4" type="video/mp4">
</video>

<p> Déplacer vers arrière le rectangle rouge de 1,00 mm sans déplacement latéralement, puis regrouper les deux rectangles.
  <br /> (Astuce : Presser la touche ⇧ SHIFT après avoir cliqué avec la souris permet de verrouiller le déplacement dans une seule direction)</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/17.mp4" type="video/mp4">
</video>

<p> Maintenant, cliquer sur la forme "biseau" et la poser sur le plan de construction. Ensuite, faire effectuer à cette forme une rotation de 90° vers le bas sur son axe vertical.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/18.mp4" type="video/mp4">
</video>

<p> Donner au biseau une hauteur de 13,50 mm et une largeur de 6,50 mm.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/19.mp4" type="video/mp4">
</video>

<p> Faire fusionner avec l'outil "aligner" le rectangle et le biseau.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/20.mp4" type="video/mp4">
</video>

<p> Surélever le rectangle de 13,50 mm pour le poser sur le biseau et regrouper les deux pièces entre elles.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/21.mp4" type="video/mp4">
</video>

<p> Aligner cette nouvelle pièce avec le cylindre précédemment extrudé.</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/22.mp4" type="video/mp4">
</video>

<p> Déplacer la pièce de 8,25 mm vers la droite et fusionner l'ensemble.
  <br /> (Lors de l'assemblage, si le moteur ne rentre pas, recommencer cette étape en modifiant la valeur en 8,5 mm )</p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/23.mp4" type="video/mp4">
</video>

<p> La pièce est maintenant terminée et prête à être imprimée !
    <br /> Sélectionner "Exporter" puis STL </p>

<video  width="auto" height="600" loop autoplay>
  <source src="https://emlyon.github.io/makerstime/Tuto01MP4/24.mp4" type="video/mp4">
</video>
    
    <br><br><br><br><br>

</font>

</body>

</html>
