<html lang="fr">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>makers' lab</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    <link href="../css/style.min.css" rel="stylesheet">

    <script src="../js/isBrightspace.js"></script>
</head>

<body>

<div class="container">

  <h1>Pour réaliser le bras du Drone avec Tinkercad :</h1>

<script src="https://embed.github.com/view/3d/emlyon/makerstime/master/STL/Drone_Arm.stl"></script>

<p> Aller sur le site <a href="https://www.tinkercad.com/">Tinkercad</a> </p>
<p> Créer votre compte puis sur le dashboard selectionner "Creer une conception" </p>

<h3>Étape 1 : Créer un cylindre </h3>

<p> Faire glisser le cylindre orange du panneau latéral de droite sur le plan de construction. </p>

<video  width="1280" height="720" >
  <source src="https://github.com/emlyon/makerstime/blob/master/Tuto01MP4/01.mp4" type="video/mp4">
  <img src="https://github.com/emlyon/makerstime/blob/master/Gifs/01.gif" type="img/gif" /></video>
</video>

<p> Cliquer sur les rectangles blancs pour donner au cylindre, une base de 10,00 mm en largeur et en profondeur (la hauteur n’a pas besoin d’être modifiée).</p>

![](Gifs/02.gif)

<p> D’autre part, il faut modifier le réglage de la grille en cliquant sur la boîte située en bas à droite et à côté de
« Grille d’accrochage 1,0 mm » et sélectionner 0,25 mm.</p>

![](Gifs/03-3.gif)

<p> Puis, sélectionner le cylindre gris dans le panneau de droite.  Toujours à l’aide des carrés blancs, il faut changer les dimensions de la base du cylindre afin de lui donner les valeurs de 7,50 mm en largeur et 7,50 mm en profondeur.</p>

![](Gifs/04.gif)

<p> À l’aide de la flèche noire au sommet, surélever le cylindre de 2,00 mm en hauteur par rapport au plan de travail.</p>

![](Gifs/05-2.gif)


<h3>Étape 2 : Extruder le cylindre orange </h3>

<p> En maintenant le bouton gauche de la souris, sélectionner les deux cylindres.  Ils devraient apparaître tous deux entourés d’un trait couleur cyan.  Appuyer sur le bouton « Aligner » ( ou bien la touche L ).
Une grille de sélection apparaît sur le rectangle au niveau du plan de travail.  Cliquer sur les cercles se situant au milieu des segments du rectangle.  Le cylindre gris se situe maintenant au milieu du cylindre orange.</p>

![](Gifs/06.gif)

<p> Sélectionner ensuite l’icône « Regrouper » en haut à droite ( ou la touche Ctrl + G ).</p>

![](Gifs/07.gif)

<p> Le cylindre orange est maintenant creux.</p>


<h3>Étape 3 : Ajouter des aérations</h3>

<p> Il faut donc prendre le cylindre gris du panneau latéral.
Grâce aux doubles flèches courbes, il est nécessaire de lui faire effectuer une rotation de 90°.</p>

![](Gifs/08.gif)

<p> Lui donner ensuite une hauteur de 7,00 mm, une largeur de 6,00 mm et une profondeur de 20,00 mm.
Grâce à la flèche noire, le surélever de 1,00 mm.</p>

![](Gifs/09.gif)

<p>Avec l’outil "Aligner", mettre le cylindre gris au centre du cylindre orange.</p>

![](Gifs/10.gif)

<p> Dupliquer le cylindre gris avec le bouton en haut à gauche ( ou bien la touche Ctrl + D ) et grâce à la flèche noire, le surélever de 10,00 mm.</p>

![](Gifs/11.gif)

<p> Sélectionner les trois cylindres et cliquer de nouveau sur « Regrouper ».</p>

![](Gifs/12.gif)

<p> Le cylindre orange est maintenant percé de quatre ovales.</p>


<h3>Étape 4 : Réaliser le bras</h3>

<p> Sélectionner la boîte rouge dans le panneau latéral droit.</p>

![](Gifs/13.gif)

<p> Après avoir placé la boîte rouge sur le plan de travail, il faut lui donner une largeur de 6,50 mm, une hauteur de 6,50 mm et une profondeur de 20,00 mm.</p>

![](Gifs/14.gif)

<p> Prendre un cube gris, il est nécessaire de lui donner les dimensions suivantes :
3,25 mm de largeur, 3,25 mm de hauteur et 10,00 mm de profondeur.</p>

![](Gifs/15.gif)

<p> Insérer le rectangle gris dans le rectangle rouge en sélectionnant les deux rectangles.  Ensuite, avec l'outil "aligner", centrer le rectangle gris au bord du rectangle rouge en cliquant sur les points noirs situés à mi-hauteur, au milieu et enfin au bord gauche du rectangle rouge.</p>

![](Gifs/16.gif)

<p> Déplacer vers arrière le rectangle rouge de 1,00 mm sans déplacement latéralement, puis regrouper les deux rectangles.
(Astuce : Presser la touche ⇧ SHIFT après avoir cliqué avec la souris permet de verrouiller le déplacement dans une seule direction)</p>

![](Gifs/17.gif)

<p> Maintenant, cliquer sur la forme "biseau" et la poser sur le plan de construction. Ensuite, faire effectuer à cette forme une rotation de 90° de sa base vers la gauche et une autre rotation de 90° vers le bas sur son axe vertical.</p>

![](Gifs/18.gif)

<p> Donner au biseau une hauteur de 13,50 mm et une largeur de 6,50 mm.</p>

![](Gifs/19.gif)

<p> Faire fusionner avec l'outil "aligner" le rectangle et le biseau.</p>

![](Gifs/20.gif)

<p> Surélever le rectangle de 13,50 mm pour le poser sur le biseau et regrouper les deux pièces entre elles.</p>

![](Gifs/21.gif)

<p> Aligner cette nouvelle pièce avec le cylindre précédemment extrudé.</p>

![](Gifs/22.gif)

<p> Déplacer la pièce de 8,25 mm vers la droite et fusionner l'ensemble.</p>

![](Gifs/23.gif)

<p> La pièce est maintenant terminée et prête à être imprimée !</p>

</body>

</html>
