<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>make a drone</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    <link href="../css/style.min.css" rel="stylesheet">

    <script src="../js/isBrightspace.js"></script>
    <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/jquery.min.js"></script>
    <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/lib/bootstrap/bootstrap.min.js"></script>
    <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/lib/vissense.min.js"></script>
    <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/app/app.js"></script>
</head>

<body>
    <div class="container">

        <div class="card-panel ">
            <h4>design & 3d print drone propeller protections</h4>
            <h5><i class="inline-icon material-icons">access_time</i> 5 hours</h5>
        </div>


        <div class="card-panel ">
            <h5>1. Create a first cylinder</h5>
            <div class="card-action">
                <p>
                    Drag and drop the orange cylinder from the right side panel onto the workplane.
                    <video width="100%" height="auto" loop autoplay muted id="video">
                        <source src="ressources/Tuto01_EngMP4/01.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Use the white squares to change the cylinder diameter size to 10.00 mm (10 mm width and 10 mm depth).<br>
                    The cylinder height does not need to be changed (20mm).
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                        <source src="ressources/Tuto01_EngMP4/02.mp4" type="video/mp4">
                    </video>
                </p>
            </div>
        </div>

        <div class="card-panel ">
            <h5>2. Dig the cylinder to create a motor holder</h5>
            <div class="card-action">
                <p>
                    Now change the setting of the grid by clicking on the box located at the bottom right of the window :<br />
                    Next to "Snap grid 1.0 mm", select 0.25 mm.
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                        <source src="ressources/Tuto01_EngMP4/03.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Then, select the grey (hollow) cylinder in the right panel.<br>
                    Also, again using the white squares, it is necessary to change the cylinder diameter to 7.50 mm width and 7.50 mm depth.
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                        <source src="ressources/Tuto01_EngMP4/04.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Using the black arrow at the top, move the cylinder 2 mm up.
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                        <source src="ressources/Tuto01_EngMP4/05.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Holding the left mouse button, select both cylinders.<br>
                    They should both appear with a cyan line.<br>
                    Press the "Align" button (or the L key).<br>
                    A selection grid appears on the rectangle at the level of the workplan, click on the circles located in the middle of the segments of the rectangle.<br>
                    The hollow cylinder is now in the middle of the orange cylinder.
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/06.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Then select the "Group" icon at the top right (or the Ctrl + G key).
                    <video width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/07.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    The orange cylinder is now hollow.
                </p>
            </div>
        </div>

        <div class="card-panel ">
            <h5>3. Add some vent to refresh motor</h5>
            <div class="card-action">
                <p>
                    Therefore, take the hollow cylinder of the side panel.<br>
                    Thanks to the double curved arrows, rotate it to 90°.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/08.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Then, you need to give it a height of 7 mm, a width of 6 mm and a depth of 20 mm.<br>
                    With the black arrow, move it 1 mm up.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/09.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    With the "align" tool, place the hollow cylinder in the center of the orange cylinder.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/10.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Duplicate the hollow cylinder with the button at the top left (or the Ctrl + D key) and with the black arrow, move it 10 mm up.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/11.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Select the three cylinders and click on "Group" again.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/12.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    The orange cylinder is now pierced by four ovals.
                </p>
            </div>
        </div>

        <div class="card-panel ">
            <h5>4. Make the drone arm</h5>
            <div class="card-action">
                <p>
                    Select the red box in the right side panel.
                    After having placed it on the workplane, it must be given a width of 6.50 mm, a height of 6.50 mm and a depth of 20 mm.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/13.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Take a grey cube, it is necessary to give it the following dimensions:<br>
                    3.25 mm width, 3.25 mm height and 10 mm depth.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/14.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Insert the hollow rectangle in the red rectangle by selecting the two rectangles<br>
                    With the "align" tool, center the hollow rectangle at the edge of the red rectangle using the black handles.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/15.mp4" type="video/mp4">
                    </video>
                <br>
                <p>
                    Move the red rectangle 1 mm backward without moving it laterally. Group the two rectangles together.<br>
                    (ProTip: Pressing the ⇧ SHIFT key after clicking with the mouse locks the movement in one direction )
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/16.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Now, click on the shape "wedge" and put it on the workplane, then perform on this form a 90° rotation on its vertical axis.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/17.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Give the wedge a height of 13.50 mm and a width of 6.50 mm.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/18.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Merge with the tool "align" the rectangle and the wedge.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/19.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Move the 13.50 mm rectangle up in order to place it on the bevel and group the two pieces together.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/20.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Align this new piece with the previously extruded cylinder.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/21.mp4" type="video/mp4">
                    </video>
                </p>
                <p>
                    Move the 8.25 mm piece to the right and merge the set.<br>
                    (During assembly, if the motor does not fit, repeat this step and try the value of 8.50 mm )
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/22.mp4" type="video/mp4">
                    </video>
                </p>
            </div>
        </div>

        <div class="card-panel ">
            <h5>5. Congratulation!</h5>
            <div class="card-action">
                <p>
                    Now you are ready to 3D Print your part 4 times!<br>
                    Select "Export" then STL<br>
                    Tip : Choose different filament color to differenciate the rear and the front of your drone.
                    <video  width="100%" height="auto" loop autoplay muted  id="video">
                      <source src="ressources/Tuto01_EngMP4/23.mp4" type="video/mp4">
                    </video>
                </p>
            </div>
        </div>
    </div>

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script src="js/init.js"></script>

</body>

</html>
